apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: ai-sno-cluster002
spec: {}
status: {}
---
apiVersion: v1
data:
  .dockerconfigjson: <your-secrets>
kind: Secret
metadata:
  name: pull-secret
  namespace: ai-sno-cluster002
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-bmh-secret
  namespace: ai-sno-cluster002
type: Opaque
data:
  username: <base64-username>
  password: <base64-password>
---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: ai-sno-cluster002
  namespace: ai-sno-cluster002
spec:
  clusterName: ai-sno-cluster002
  clusterImageSetNameRef: img4.17.4-x86-64-appsub
  baseDomain: balk.ocp.local
  machineNetwork:
    - cidr: 192.168.4.0/22
  networkType: OVNKubernetes
  sshPublicKey: <your-ssh-key>
  pullSecretRef:
    name: pull-secret
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management
  nodes:
    - role: master
      hostName: ai-sno-cluster002
      bmcAddress: redfish-virtualmedia+http://192.168.7.126:8000/redfish/v1/Systems/deed1e55-fe11-f0e5-0dd5-babb1ed1a011
      bmcCredentialsName:
        name: ai-bmh-secret
      bootMACAddress: "00:00:00:00:00:11"
      bootMode: UEFI
      automatedCleaningMode: disabled
      cpuArchitecture: x86_64
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
      nodeNetwork:
        interfaces:
          - name: ens1s0
            macAddress: "00:00:00:00:00:11"
        config:
          interfaces:
            - name: ens1s0
              type: ethernet
              state: up
              ipv4:
                enabled: true
                dhcp: false
                address:
                  - ip: 192.168.7.11
                    prefix-length: 24
              ipv6:
                enabled: false
          dns-resolver:
            config:
              search:
                - balk.ocp.local
              server:
                - 192.168.7.126
                - 8.8.8.8
          routes:
            config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.4.1
                next-hop-interface: ens1s0
                table-id: 254
